#!/usr/bin/env python3
"""
Writes constants/icon-names.ts with name → codepoint maps read from the bundled icon fonts.

The outlined and filled static instances do not share codepoints for every icon, so each map is
derived from that font's own ligature table (name → glyph) and cmap (glyph → private-use codepoint).
Needs fontTools: `python3 -m pip install fonttools`. Run by scripts/icon-subset.mjs.
"""
import json
import os
import sys

from fontTools.ttLib import TTFont

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
FONTS = {"ICON_CODEPOINTS": "MaterialSymbolsRounded.ttf", "ICON_CODEPOINTS_FILLED": "MaterialSymbolsRoundedFilled.ttf"}


def names_to_codepoints(path):
    font = TTFont(path)
    cmap = font.getBestCmap()
    glyph_to_cp = {}
    for cp, glyph in cmap.items():
        if cp >= 0xE000:
            glyph_to_cp.setdefault(glyph, cp)
    glyph_to_char = {glyph: chr(cp) for cp, glyph in cmap.items() if cp < 0x80}
    out = {}
    for lookup in font["GSUB"].table.LookupList.Lookup:
        for sub in lookup.SubTable:
            table = getattr(sub, "ExtSubTable", sub)
            ligatures = getattr(table, "ligatures", None)
            if ligatures is None:
                continue
            for first, ligs in ligatures.items():
                for lig in ligs:
                    try:
                        name = "".join(glyph_to_char[g] for g in [first] + lig.Component)
                    except KeyError:
                        continue
                    if lig.LigGlyph in glyph_to_cp:
                        out[name] = glyph_to_cp[lig.LigGlyph]
    return dict(sorted(out.items()))


def main():
    maps = {const: names_to_codepoints(os.path.join(ROOT, "assets", "fonts", fn)) for const, fn in FONTS.items()}
    lines = [
        "// Generated by scripts/icon-codepoints.py (via scripts/icon-subset.mjs) — do not edit.",
        "// Icons are drawn by codepoint, not ligature: native text drops ligatures under letterSpacing or",
        "// when nested in styled text. The filled instance has its own codepoints for some icons.",
    ]
    for const, m in maps.items():
        lines.append(f"export const {const}: Record<string, number> = {json.dumps(m, separators=(',', ':'))};")
    lines.append("export const ICON_NAMES = new Set(Object.keys(ICON_CODEPOINTS));")
    with open(os.path.join(ROOT, "constants", "icon-names.ts"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"[icon-codepoints] outlined {len(maps['ICON_CODEPOINTS'])} · filled {len(maps['ICON_CODEPOINTS_FILLED'])}")


if __name__ == "__main__":
    sys.exit(main())
